# Generated by Django 3.2.6 on 2021-08-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=15)),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('grade_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=40)),
                ('birth_day', models.DateTimeField()),
                ('img', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('certificate', models.FileField(upload_to='')),
                ('teach_grade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=40)),
                ('birth_day', models.DateTimeField()),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.grade')),
            ],
        ),
    ]
