# Generated by Django 3.2.6 on 2021-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
