# Generated by Django 3.2.6 on 2021-08-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_pupil_birth_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=40)),
                ('birth_day', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('certificate', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)]),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teach_grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='school_app.grade'),
        ),
    ]
