# Generated by Django 3.2.6 on 2021-08-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20210808_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teach_grade',
        ),
    ]
