# Generated by Django 3.2.6 on 2021-08-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_teacher_teach_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('subject_in_school', models.CharField(choices=[('math', 'math'), ('native_language', 'native_language'), ('physics', 'physics')], max_length=20)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.pupil')),
            ],
        ),
        migrations.DeleteModel(
            name='Dairy',
        ),
    ]
