# Generated by Django 3.2.6 on 2021-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
