# Generated by Django 3.2.6 on 2021-08-11 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_auto_20210811_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='contact',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(13)]),
        ),
    ]
